# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt  
# spec:
#   acme:
#     email: kishorebsc12@gmail.com
#     server: https://acme-v02.api.letsencrpt.org/directory
#     privateKeySecretRef:
#       name: letsencrypt
#     solvers:
#     - http01:
#         ingress:
#           class: nginx

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt  # ✅ Corrected name
spec:
  acme:
    email: ykishorebsc12@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
