name: Terraform apply
on: [workflow_dispatch]
jobs:
  Terraform-init:
    runs-on: [self-hosted]
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Terraform init
        run:  |    
          terraform init -reconfigure -backend-config=env-dev/state.tfvars
          # terraform init -backend-config=env-dev/state.tfvars
#   Terraform-plan:
#     runs-on: self-hosted
#     steps:
#       - name: checkout repo
#         uses: actions/checkout@v4
#       - name: Terraform plan
#         run: |
#           terraform plan -var-file=env-dev/main.tfvars
  Terraform-apply:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name:   Terraform apply
        run: |
          terraform apply -var-file=env-dev/main.tfvars