name: Terraform apply
on: [workflow_dispatch]
jobs:
  # Terraform-init:
  #   runs-on: [self-hosted]
  #   steps:
  #     - name: checkout repo
  #       uses: actions/checkout@v4
  #     - name: Terraform init
  #       run:  |    
  #         terraform init -reconfigure -backend-config=env-dev/state.tfvars
  #         # terraform init -backend-config=env-dev/state.tfvars
  # Terraform-plan:
  #   runs-on: self-hosted
  #   steps:
  #     - name: checkout repo
  #       uses: actions/checkout@v4
  #     - name: Terraform plan
  #       run: |
  #         terraform plan -var-file=env-dev/main.tfvars 2>&1 | tail -n6 | head -n1 >$GITHUB_STEP_SUMMARY
  # Terraform-apply:
  #   runs-on: self-hosted
  #   steps:
  #     - name: checkout repo
  #       uses: actions/checkout@v4
  #     - name:   Terraform apply
  #       run: |
        
  #         terraform init -upgrade -backend-config=env-dev/state.tfvars
  #         terraform apply -var-file=env-dev/main.tfvars -var vault_token=${vault_token} -auto-approve
  #       env:
  #         vault_token: ${{ secrets.vault_token }}

  Deploy-cart:
    runs-on: self-hosted
    # needs: Terraform-apply
    steps:
      - name:  checkout repo 
        uses:  actions/checkout@v4
        with:
          repository: Thippareddykishor/roboshop-cart
          path: app
      - name:  checkout repo
        uses: actions/checkout@v4
        with:
          repository: Thippareddykishor/roboshop-helm
          path: helm
      - name: install Helm
        run: |
          aws eks update-kubeconfig --name dev
          cd app
          GID=$(git log --format="%H" -n 1)
          cd ../helm
          bash argocd.sh cart dev $GID
  
  Deploy-catalogue:
    runs-on: self-hosted
    # needs: Terraform-apply
    steps:
      - name:  checkout repo 
        uses:  actions/checkout@v4
        with:
          repository: Thippareddykishor/roboshop-catalogue
          path: app
      - name:  checkout repo
        uses: actions/checkout@v4
        with:
          repository: Thippareddykishor/roboshop-helm
          path: helm
      - name: install Helm
        run: |
          aws eks update-kubeconfig --name dev
          cd app
          GID=$(git log --format="%H" -n 1)
          cd ../helm
          bash argocd.sh cart dev $GID
  
  Deploy-User:
    # needs: Terraform-apply
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          repository: Thippareddykishor/roboshop-user
          path: app
      - name: checkout code
        uses: actions/checkout@v4
        with:
          repository:  Thippareddykishor/roboshop-helm
          path: helm
      - name: install helm
        run: |
            aws eks update-kubeconfig --name dev
            cd app
            GID=$(git log --format="%H" -n 1)
            cd ../helm
            bash argocd.sh user dev $GID
  
  Deploy-shipping:
    runs-on: self-hosted
    # needs: Terraform-apply
    steps:
      - name:  checkout repo 
        uses:  actions/checkout@v4
        with:
          repository: Thippareddykishor/roboshop-shipping
          path: app
      - name:  checkout repo
        uses: actions/checkout@v4
        with:
          repository: Thippareddykishor/roboshop-helm
          path: helm
      - name: install Helm
        run: |
          aws eks update-kubeconfig --name dev
          cd app
          GID=$(git log --format="%H" -n 1)
          cd ../helm
          bash argocd.sh cart dev $GID

  
  Deploy-Payment:
    # needs: Terraform-apply
    runs-on: self-hosted
    steps:
      - name: checkout repo code
        uses: actions/checkout@v4
        with:
          repository: Thippareddykishor/roboshop-payment
          path: app
      - name: checkout code
        uses: actions/checkout@v4
        with:
          repository: Thippareddykishor/roboshop-helm
          path: helm
      - name: helm install
        run: |
          aws eks update-kubeconfig --name dev
          cd app
          GID=$(git log --format="%H" -n 1)
          cd ../helm
          bash argocd.sh payment dev $GID

  Deploy-frontend:
    runs-on: self-hosted
    # needs: Terraform-apply
    steps:
      - name:  checkout repo 
        uses:  actions/checkout@v4
        with:
          repository: Thippareddykishor/roboshop-frontend
          path: app
      - name:  checkout repo
        uses: actions/checkout@v4
        with:
          repository: Thippareddykishor/roboshop-helm
          path: helm
      - name: install Helm
        run: |
          aws eks update-kubeconfig --name dev
          cd app
          GID=$(git log --format="%H" -n 1)
          cd ../helm
          bash argocd.sh cart dev $GID


  # Helm-install-application: 
  #   # needs: Terraform-apply
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout repo
  #       uses: actions/checkout@v4
  #       with:
  #         repository: Thippareddykishor/roboshop-cart
  #         # path: helm
  #     - name: terraform apply
  #       run:  |
  #         git log --format ="%H" -n 1
  #         # cd helm
  #         # aws eks update-kubeconfig  --name dev
  #         # make dev
  #         # gh workflow ls
  #         # gh workflow run ci-main.yml
  #       env:
  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}